name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    workflow_dispatch:
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! 
      - name: java version
        run: java -version
      - name: maven version
        run: mvn --version
      - name: docker version
        run: docker -v
      - name: terraform version
        run: terraform --version
 
